import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import "./globals.css";
import SideNav from "@/components/SideNav";
import { Providers } from "@/app/providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen font-sans antialiased", inter.variable)}
      >
        <Providers>
          <div className="flex flex-row font-mono text-slate-100">
            <SideNav />
            <div className="app max-h-screen w-full overscroll-none font-mono">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
